
def en():
    global name,done_message, current_language,message2, yes_, message_en, message_ar, cancel_, no_, exe_icon_path_x, exe_icon_path_y, font_3, exe_icon_path_t, exe_text, exe_x, exe_y, enc_y, enc_x, enc_text, en, ar, lang, LOGO, dishok, type_, font_, x_inFile, y_inFile, x_inhook, y_inhook, type_x, type_y, full_info, wifi_info_y, wifi_info_x, font_2, ssids_pass_only, ssids_pass_only_x, ssids_pass_only_y, title_, set_full, set1_x, set1_y, set_user_pass, set2_x, set2_y, execute, execute_x, execute_y, About_, settings_, update, about__, lab_logo_x, lab_logo_y
    done_message="the process has been completed successfully"
    message2 = "You can't select both options"
    en = "English"
    ar = "Arbic"
    lang = "language"
    LOGO = 'images\\logo.png'
    title_ = "Storm wifi-Grabber"
    name = "File name"
    dishok = "Discord webhook"
    type_ = "grabber type"
    full_info = "All profile settings: SSIDs, passwords, encryption, authentication,etc."
    ssids_pass_only = "Network credentials: SSIDs and passwords only."
    set_full = "Set"
    execute = "execute"
    settings_ = "Settings"
    About_ = "About"
    update = "Update"
    about__ = "version 2.1"
    enc_text = "Obfuscation"
    exe_text = "Export as exe"
    exe_icon_path_t = "icon Path"
    yes_ = "Yes"
    no_ = "No"
    cancel_ = "Cancel"
    message_ar = "Do you want to change the language to arbic?"
    message_en = "Do you want to change the language to english?"
    x_inFile = 30
    y_inFile = 55
    x_inhook = 30
    y_inhook = 175
    type_x = 30
    type_y = 300
    wifi_info_x = 20
    wifi_info_y = 360
    ssids_pass_only_x = 20
    ssids_pass_only_y = 400
    set1_x = 930
    set1_y = 360
    set2_x = 600
    set2_y = 400
    execute_x = 850
    execute_y = 600
    lab_logo_x = 650
    lab_logo_y = 5
    enc_x = 30
    enc_y = 500
    exe_x = 250
    exe_y = 500
    exe_icon_path_x = 30
    exe_icon_path_y = 550
    font_ = (("Castellar", 40))
    font_2 = (("Courier New", 20))
    font_3 = (("Courier New", 15))
    current_language = "en_glish"
en() 